import { hash, verify, type Options } from '@node-rs/argon2';
import {
  passwordDigest,
  type PasswordDigest,
} from '../../domain/credential/secrets';

/**
 * Argon2id, because passwords are chosen by humans and therefore guessable at
 * a rate a fast hash cannot survive. The cost parameters are configuration
 * rather than constants: the right values depend on the machine, and a number
 * baked into source is a number nobody ever revisits.
 */
export interface HashingConfig {
  readonly memoryCostKiB: number;
  readonly timeCost: number;
  readonly parallelism: number;
}

/** The OWASP baseline for Argon2id, used when nothing is configured. */
const BASELINE: HashingConfig = {
  memoryCostKiB: 19456,
  timeCost: 2,
  parallelism: 1,
};

type Env = Record<string, string | undefined>;

/**
 * The library declares its algorithms as an ambient `const enum`, which
 * `isolatedModules` forbids reading — the build fails even though the tests,
 * which transpile without type-checking, do not. Naming the value here keeps
 * the choice explicit rather than falling back on the library's default, which
 * is what a security parameter deserves.
 */
const ARGON2ID: NonNullable<Options['algorithm']> = 2;

export function loadHashingConfig(env: Env): HashingConfig {
  return {
    memoryCostKiB: positiveInteger(
      env.AUTH_ARGON2_MEMORY_KIB,
      'AUTH_ARGON2_MEMORY_KIB',
      BASELINE.memoryCostKiB,
    ),
    timeCost: positiveInteger(
      env.AUTH_ARGON2_TIME_COST,
      'AUTH_ARGON2_TIME_COST',
      BASELINE.timeCost,
    ),
    parallelism: positiveInteger(
      env.AUTH_ARGON2_PARALLELISM,
      'AUTH_ARGON2_PARALLELISM',
      BASELINE.parallelism,
    ),
  };
}

function positiveInteger(
  raw: string | undefined,
  key: string,
  fallback: number,
): number {
  const value = raw?.trim();
  if (value === undefined || value.length === 0) {
    return fallback;
  }
  const parsed = Number(value);
  if (!Number.isInteger(parsed) || parsed <= 0) {
    throw new Error(`${key} must be a positive integer, got "${value}"`);
  }
  return parsed;
}

export class Argon2PasswordHasher {
  private decoy: Promise<PasswordDigest> | undefined;

  constructor(private readonly config: HashingConfig) {}

  /**
   * Verifies against a digest that matches nothing, at full cost.
   *
   * Sign-in calls this when the address is unknown or has no password. Skipping
   * the comparison would make those paths measurably faster than a wrong
   * password, and response time would answer the question the response body
   * refuses to. The decoy is computed once and reused: it is not a secret, only
   * a way to spend the same time.
   */
  async verifyAgainstDecoy(password: string): Promise<false> {
    this.decoy ??= this.hash('a value no account will ever hold');
    await this.verify(password, await this.decoy);
    return false;
  }

  async hash(password: string): Promise<PasswordDigest> {
    // The salt is generated by the library per call, which is why two hashes of
    // the same password differ and why no digest can be looked up in a table.
    const digest = await hash(password, {
      algorithm: ARGON2ID,
      memoryCost: this.config.memoryCostKiB,
      timeCost: this.config.timeCost,
      parallelism: this.config.parallelism,
    });
    return passwordDigest(digest);
  }

  /**
   * A digest that cannot be parsed is a failed verification, not an exception.
   * A truncated column or a value written by something else must look exactly
   * like a wrong password from the outside; letting it throw would give a
   * caller a way to tell the two apart.
   */
  async verify(password: string, digest: PasswordDigest): Promise<boolean> {
    try {
      return await verify(digest, password);
    } catch {
      return false;
    }
  }
}
